column1_background=1
column1_font_color=2
column2_background=3
column2_font_color=4

default_column1_background=2
default_column1_font_color=4
default_column2_background=5
default_column2_font_color=1
